packages:
  - packages/*
  - test_app
  - packages/mcp-use/examples/client/react
  - packages/mcp-use/examples/server/simple
  - packages/create-mcp-use-app/src/templates/starter
  - packages/create-mcp-use-app/src/templates/mcp-ui
  - packages/create-mcp-use-app/src/templates/apps-sdk
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
